name: Documentation
on:
    push:
        branches:
          - main
jobs:
  docs:
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Nvidia Container Toolkit
        run: |
            distribution=$(. /etc/os-release;echo $ID$VERSION_ID)
            curl -fsSL https://nvidia.github.io/libnvidia-container/gpgkey | sudo gpg --dearmor -o /usr/share/keyrings/nvidia-container-toolkit-keyring.gpg
            curl -s -L https://nvidia.github.io/libnvidia-container/$distribution/libnvidia-container.list | sed 's#deb https://#deb [signed-by=/usr/share/keyrings/nvidia-container-toolkit-keyring.gpg] https://#g' | sudo tee /etc/apt/sources.list.d/nvidia-container-toolkit.list
            sudo apt-get update
            sudo apt-get install -y nvidia-docker2 nvidia-container-toolkit
            sudo systemctl restart docker
      - name: Pre-build image and build documentation in dev container
        uses: devcontainers/ci@v0.2
        with:
          imageName: ghcr.io/michellechaochen/error-estimate-for-fem-devcontainer
          cacheFrom: ghcr.io/michellechaochen/error-estimate-for-fem-devcontainer
          push: always
          runCmd: cd docs && make html
      - name: Configure GitHub Pages
        uses: actions/configure-pages@v3.0.0
      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v1.0.7
        with:
          path: docs/build/html
      - name: Deploy GitHub Pages site
        uses: actions/deploy-pages@v1.2.3
